seed_everything: 7
trainer:
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: ./       # <-- 这个是必须的
      name: lightning_logs      # 日志文件夹名称（可选）
      version: null             # 版本号自动生成
  # checkpoint_callback: true
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 1
        monitor: val_ExpRate
        mode: max
        filename: '{epoch}-{step}-{val_ExpRate:.4f}'
  accelerator: gpu
  devices: [0]
  # strategy: ddp
  strategy: ddp_find_unused_parameters_true

  gradient_clip_val: 1.0  # 梯度裁剪阈值
  gradient_clip_algorithm: 'norm'  # 使用 L2 范数裁剪

  check_val_every_n_epoch: 2
  max_epochs: 301
model:
  encoder_type: mit0  # DenseNet, 
  d_model: 256
  # encoder
  growth_rate: 24
  num_layers: 16
  # decoder
  nhead: 8
  num_decoder_layers: 3
  dim_feedforward: 1024
  dropout: 0.3
  dc: 32
  cross_coverage: true
  self_coverage: true
  # beam search
  beam_size: 10
  max_len: 100
  alpha: 1.0
  early_stopping: false
  temperature: 1.0
  # training
  learning_rate: 0.08
  patience: 20
  warmup_steps: 500
  max_epochs: 501
  # encoder transformer
  encoder_nhead: 8
  encoder_num_layers: 3
  encoder_dim_feedforward: 1024
  encoder_dropout: 0.3
data:
  zipfile_path: ./data.zip
  test_year: '2014'
  train_batch_size: 8
  eval_batch_size: 2
  num_workers: 0
  scale_aug: true