_instantiator: lightning.pytorch.cli.instantiate_module
alpha: 1.0
beam_size: 10
cross_coverage: true
d_model: 256
dc: 32
dim_feedforward: 1024
dropout: 0.3
early_stopping: false
encoder_dim_feedforward: 1024
encoder_dropout: 0.3
encoder_nhead: 8
encoder_num_layers: 3
encoder_type: mit0
growth_rate: 24
learning_rate: 0.16
max_epochs: 501
max_len: 100
nhead: 8
num_decoder_layers: 3
num_layers: 16
patience: 20
self_coverage: true
temperature: 1.0
warmup_steps: 500
